### ISSUE TITLE
Application links in Application Profile should open a new window when they are external but open internally when they are hub applications

### ISSUE THREAD

**Issue by cpeach-tnrd** [tnrdit/tnrd-hub#17]
https://hub.tnrdit.ca/content/applications/613a5282f8c0135ddd51f3a4 for example should open in same tab, but links in https://hub.tnrdit.ca/content/applications/614514e7d2abf06f8940c85b should open in a new tab.

**Comment by jphillips-tnrd** [comment]
Pushed this one.
