### ISSUE TITLE
Placeholder not showing in Select field.

### ISSUE THREAD

**Issue by cpeach-tnrd** [tnrdit/tnrd-hub#6]
In the component /components/form/fields/select.jsx there is an option for placeholder. See https://ant.design/components/select/ . For whatever reason, when you add the placeholder prop. it doesn't reflect in the UI.

**Comment by jphillips-tnrd** [comment]
Is this one working now?

**Comment by cpeach-tnrd** [comment]
Yes, this one was resolved.
